# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: src/generic
project_affiliation: gabyx
project_authors:
-   email: alice.wonderland@sdsc.ethz.ch
    first_name: Alice
    last_name: Wonderland
-   email: bob.wonderland@sdsc.ethz.ch
    first_name: Bob
    last_name: Wonderland
project_description: Test example for NAT traversal with Rust. A learning project.
project_hosts:
-   host: github.com
    organization: gabyx
    repo: socket-rs
project_language: rust
project_license: mit
project_name: socket-rs
project_url: https://github.com/gabyx/socket-rs
project_version: 0.0.1
