# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: src/rust
executable_name: main
library_name: common-lib
project_authors:
-   email: alice.wonderland@sdsc.ethz.ch
    first_name: Alice
    last_name: Wonderland
-   email: bob.wonderland@sdsc.ethz.ch
    first_name: Bob
    last_name: Wonderland
project_description: Test example for NAT traversal with Rust. A learning project.
project_url: https://github.com/gabyx/socket-rs
project_version: 0.0.1
